address: https://test-stand.gb.ru
browser: chrome
sleep: 1
implicitly_wait: 3
login: "Friday"
password: "c33b138a16"
url: https://test-stand.gb.ru/gateway/login
url_api: https://test-stand.gb.ru/api/users/profile/
